### ISSUE TITLE
Implement Submodel of Part Type Information

### ISSUE THREAD

**Issue by f-zimmer** [eclipse-tractusx/puris#180]
**As a** PURIS admin (supplier side),
**I want** provide the Part Type Information if not present
**so that** I be compliant to the industry core.

## Hints / Details

Overall target: Add capabilities for PartTypeInformation (SAMM) mapping from / to Material Entity. 

The Part Type Information represents the "Catalog Item" in Catena-X, which is a Submodel of a Digital Twin.

It's currently renamed (from PartAsPlanned) to a new version with some changes. Follow this [Issue](https://github.com/eclipse-tractusx/sldt-semantic-models/issues/591) (subscription in github).

We only need to provide the mandatory information:
- Catena-X ID
- partTypeInformation.nameAtManufacturer
- partTypeInformation.manufacturerPartId

The fields `partClassification` and `partSitesInformationAsPlanned` are NOT relevant.

We'll need the model for the following cases:
- Customer: Get Catena-X ID of a Supplier, when creating a digital Twin in the DTR.
- Supplier: Create a PartSiteInformation and register it as Submodel when creating the Twin -> only map your material information

- Download [SAMM CLI](https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/samm-cli.html) and make it executable (follow instructions)
- clone sldt-semantic-models repository, go to folder with suffix name "part_type_information" and generate java pojo for latest version `samm <aspect model> to java -o <some directory>`
- Update files to match package masterdata/logic/dto/samm (do it similarly as [ItemStock](https://github.com/eclipse-tractusx/puris/tree/main/backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/dto/itemstocksamm) that has been created based on this [model](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.item_stock))
- Create a Samm Mapper (similar to [item stock](https://github.com/eclipse-tractusx/puris/blob/main/backend/src/main/java/org/eclipse/tractusx/puris/backend/stock/logic/adapter/ItemStockSammMapper.java)) that maps the MaterialEntity to this PartAsPlanned.
  - focus on mandatory fields
  - you can refer to the `gen` folder of the part_as_planned to check the definitions in html and see example payloads.

### Outcome
- ...
### Acceptance Criteria
- part as planned data can be mapped to and from material data
- submodel endpoint can provision part as planned

## Out of Scope

- ...

**Comment by tom-rm-meyer-ISST** [comment]
Refinements:

- The `Material` Entity needs a further attribute `classification` as described in the PartAsPlanned (enumeration). -> Existing materials shall be set to `product` in test data creation (`DataInjectionCommandLineRunner`, Postman collection)
- The `MaterialPartnerRelationship` needs a further attribute `description` so that one always have a an information `manufacturerPartName` -> the id is always known by either `Material.ownMaterialNumber` or `MaterialPartnerRelationship.partnerMaterialNumber`
- A PartAsPlanned needs to be mapped from Material and MaterialPartnerRelationship. That means that we need to have the mapping depending on a partner.
- When enhancing the material, we also need to update the masterdata controllers and services.
