### ISSUE TITLE
Legal Documentation and Dependencies file

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/puris#49]
## Legal documentation
After merging frontend and backend into a sinlge mono repo, the legal documentation in backend/frontend folder is obsolete as this is expected at repos top level.

## DEPENDENCIES file
Please ensure to keep you `DEPENDENCIES`, `DEPENDENCIES_BACKEND` `DEPENDENCIES_FRONTEND` files in repos top level up to date. Currently `backend/DEPENDENCIES`and `frontend/DEPENDENCIES` are newer than the top level `DEPENDENCIES_*`files. It is essential to keep the dependencies to used third-party libraries/components up to date!

**Comment by tom-rm-meyer-ISST** [comment]
Hi @carslen, thanks for raising the issue!

That's actually by intention to fulfill the legal requirements during build processes. According to [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) one MUST include the respective files in the distributables (jar, container). As some of the building tools (I think docker) mustn't / can't access the parent directory, I moved the files to the respective folder.

That dependencies are out of sync is actually a problem. We sometime noticed that and try to handle with more rigorous handling and reviewing. Maybe we'll update our PR template to include both places or add a script for that.

Do you have ideas on how to tackle it differently / better? Maybe that's something we could discuss in the office hour (but I would need to handover that topic to Malte as I won't be available the next two weeks).

**Comment by tom-rm-meyer-ISST** [comment]
To solve this issue and still follow [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05), the proposal during dev sec ops team was as follows: adjust docker build workflow to copy the legal documentation to the respective folder and include it during build.

We still need to be able to build the file locally. Maybe we can also parametrize the dockerfile to include the documentation when publishing so that we can build the file
- within folder same as today
- from root with copying files in the workflow and then include them as currently done in the frontend and backend.

Maybe this [repository](https://github.com/eclipse-tractusx/traceability-foss/blob/9d49d92ffc6a7121d6e0a9cc35dee22fc943331b/frontend/Dockerfile) provides some inspiration.

**Comment by tom-rm-meyer-ISST** [comment]
Closed with #389
