### ISSUE TITLE
Rework handling of creation for yourself as a partner

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/puris#525]
## Current behaviour

During Startup currently we always create a partner for yourself and offers in the edc for this partner.

## Expected behavior

- If a partner with the BPNL is present we should not overwrite it (likely already done).
- Don't create assets in that case

## Steps to reproduce the Bug

- configure yourself in properties
- start application > logs indicate partner creation

**Comment by eschrewe** [comment]
Hmm, I am not sure, if I understand this correctly... 

A few points: 

- The DataInjectionCommandlineRunner always calls the createOwnPartnerEntity() method. 
- That method uses the data from the properties file (Name ,BPNL, BPNS, etc...) 
- and sends a "create" call to the PartnerService. 
- The PartnerServiceImpl's create method is already checking, whether the given Partner Object's BPNL already exists in the database (see line 74 of the  PartnerServiceImpl class. If yes, then nothing is written to the database (line 78, 79)

So, from my understanding, the current implementation is already doing, what you are stating in the "Expected behaviour" section in that regard. 

Beyond that, you are stating, that no assets should be created in a case, where the "ownPartnerEntity" already existed in the database. 

But I don't think, that this is sensible or necessary. The assets are created on the control plane. From the puris backend's perspective, we can't know for sure, which assets were already registered on the control plane during a previous session of the puris backend. But even if they do already exist on the control plane, it is not harmful to try to create them again. In that case, the control plane may return an error message "Asset with that id already exists". But that is not a problem. It would be far worse, if - in the other case- those assets are possibly not created. Then the entire puris backend would be unable to receive any partner messages.

**Comment by tom-rm-meyer-ISST** [comment]
First regarding creation of the own partner entity is great. Thanks for analysis!

Second is a question of operating. As operator it confuses to see that the asset registration failed and then just read that there is an ObjectConflict. It's not hurting, but it be more handsome to not have errors in the logs but just a statement like "No EDC assets created for xyz submodel as it already exists.".

Thus, it would be a small cosmetics change.
