### ISSUE TITLE
Security: Input validation

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/puris#95]
Currently there are fields in the persistance layer that have no pattern restrictions. Pattern restrictions should be applied to all fields to ensure data integrity and prevent e.g. injection possibilities.

MUST: pattern validations in persistance level
SHOULD: 
- businesswise validations, if not already in place on service layer
- escaping variables in log messages.

**Comment by eschrewe** [comment]
Could you please update the specific tasks of this issue? As far as I remember, we had discussed that that avoidance of SQL injections was not a must, since we are are only receiving input data from the frontend under password protection. From my point of view, we are only talking about input validation here in the context of protecting the business logic?

**Comment by tom-rm-meyer-ISST** [comment]
I updated the description. Pattern validations on persistance layer are a MUST criteria for all entities. This ensures data integrity and should reduce sql injection potentials (e.g. we don't need backslashs or ' " in any field).

**Comment by eschrewe** [comment]
Hmm, but we have currently some Entites that are clearly outdated, like for instance 
org.eclipse.tractusx.puris.backend.common.edc.domain.model,ExternalConnector
or anything in the 
org.eclipse.tractusx.puris.backend.model.* - package
or
org.eclipse.tractusx.puris.backend.common.api.domain.repository.MessageRepository

I'd say we skip those, since these are bound to be removed soon anyways?
